CREATE TABLE IF NOT EXISTS adgroup_criteria (
  id                   SERIAL,
  criteria_exchange_id BIGINT NOT NULL,
  account_id           BIGINT NOT NULL,
  account_exchange_id  BIGINT NOT NULL,
  campaign_id          BIGINT NOT NULL,
  campaign_exchange_id BIGINT NOT NULL,
  adgroup_id           BIGINT NOT NULL,
  adgroup_exchange_id  BIGINT NOT NULL,
  criteria_type        VARCHAR,
  status               VARCHAR,
  term                 VARCHAR,
  match_type           VARCHAR,
  final_url            VARCHAR,
  labels               VARCHAR,
  hash                 VARCHAR,
  updated              TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  FOREIGN KEY (account_id) REFERENCES account (id) ON UPDATE NO ACTION ON DELETE NO ACTION,
  FOREIGN KEY (campaign_id) REFERENCES campaign (id) ON UPDATE NO ACTION ON DELETE NO ACTION,
  FOREIGN KEY (adgroup_id) REFERENCES adgroup (id) ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS temp_adgroup_criteria (
  id                   SERIAL,
  criteria_exchange_id BIGINT NOT NULL,
  account_id           BIGINT NOT NULL,
  account_exchange_id  BIGINT NOT NULL,
  campaign_id          BIGINT NOT NULL,
  campaign_exchange_id BIGINT NOT NULL,
  adgroup_id           BIGINT NOT NULL,
  adgroup_exchange_id  BIGINT NOT NULL,
  criteria_type        VARCHAR,
  status               VARCHAR,
  term                 VARCHAR,
  match_type           VARCHAR,
  final_url            VARCHAR,
  labels               VARCHAR,
  hash                 VARCHAR,
  PRIMARY KEY (id),
  FOREIGN KEY (account_id) REFERENCES temp_account (id) ON UPDATE NO ACTION ON DELETE NO ACTION,
  FOREIGN KEY (campaign_id) REFERENCES temp_campaign (id) ON UPDATE NO ACTION ON DELETE NO ACTION,
  FOREIGN KEY (adgroup_id) REFERENCES temp_adgroup (id) ON UPDATE NO ACTION ON DELETE NO ACTION
);
