ALTER TABLE account ALTER COLUMN updated SET DATA TYPE TIMESTAMP WITH TIME ZONE;
ALTER TABLE campaign ALTER COLUMN updated SET DATA TYPE TIMESTAMP WITH TIME ZONE;
ALTER TABLE adgroup ALTER COLUMN updated SET DATA TYPE TIMESTAMP WITH TIME ZONE;
ALTER TABLE keyword ALTER COLUMN updated SET DATA TYPE TIMESTAMP WITH TIME ZONE;
ALTER TABLE adgroup_criteria ALTER COLUMN updated SET DATA TYPE TIMESTAMP WITH TIME ZONE;
